- name: adding apache in firewalld
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state:  enabled

- name: adding database in firewalld
  firewalld: 
    service: mysql 
    permanent: yes
    immediate: yes 
    state: enabled
