- name: setting MySQL root account password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    user: "root"
    login_password: '{{mysql_pass}}'
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present

- name: create a new database - wordpress
  mysql_db: name=wordpress state=present login_user=root

- name: create a new database user - wordpressuser
  mysql_user:
    name: wordpressuser
    password: wuser
    priv: '*.*:ALL,GRANT'
    state: present


