- name: Update DNF Package repository cache
  dnf:
     update_cache: True
- name: Install MySQL server on RHEL/CENTOS 8
  dnf:
     name: mysql-server
     state: present
- name: Install MySQL client on RHEL/CENTOS 8
  dnf:
     name: mysql
     state: present
- name: Make sure mysqld service is running
  service:
     name: mysqld
     state: started
     enabled: True
- name:
  yum:
    name: php-gd
    state: present

- name: Install python3-PyMySQL library
  dnf:
    name: python3-PyMySQL
    state: present

