- name: Installing apache and php requirement packages
  yum:
    name: "{{item}}"
    state: present 
  loop: 
    - httpd
    - php
    - php-cli
    - php-gd 
    - php-mysqlnd
    - php-mbstring
    - php-opcache
- name: Installing packages for database
  yum:
    name: "{{item}}"
    state: present
  loop: 
    - mariadb-server
    - mariadb
- name: Installing requirement packages for database
  dnf:
    name: python3-PyMySQL
    state: present
- name: Starting service of database: mysql
  service:
    name: mariadb
    state: started
    enabled: True
