- name: 
  yum:
    name: "{{item}}"
    state: present 
  loop: 
    - httpd
    - php
    - php-cli
    - php-gd 
    - php-mysqlnd
    - php-mbstring
    - php-opcache
- name: Install MySQL server on RHEL/CENTOS 8
  yum:
    name: "{{item}}"
    state: present
  loop: 
    - mariadb-server
    - mariadb
- dnf:
    name: python3-PyMySQL
    state: present
- name: Starting mysql service 
  service:
    name: mariadb
    state: started
    enabled: True
