---
- name: Set up Apache VirtualHost
  template:
    src: "files/httpd.conf"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/html"
    remote_src: yes
    creates: "/var/www/html/wordpress"

- name: Set ownership
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes
    owner: apache
    group: apache

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/html/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/html/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Copy sample config file
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
    path: "/var/www/html/wordpress/wp-config.php"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', 'wordpress' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', 'black' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{new}}' );"}192.168.0.211
 
- name: Restart httpd service
  systemd: name=httpd state=restarted
  become: yes
- name: Disable SELinux Permanently (Reboot Required)
  selinux: state=disabled

- name: Disable SELinux Without Reboot
  command: /sbin/setenforce 0
