- name:  installing packages 
  yum: 
    name: ['php', 'php-mcrypt', 'php-cli', 'php-gd', 'php-curl', 'php-mysql', 'php-ldap', 'php-zip', 'php-fileinfo']
    enablerepo: "remi-php73"
    state: present 

