- name: 
  yum: 
    name: epel-release
    state: present 
- name: 
  yum: 
    name: yum-utils 
    state: present 
- name: 
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
- name:  installing packages 
  yum: 
    name: ['php', 'php-mcrypt', 'php-cli', 'php-gd', 'php-curl', 'php-mysql', 'php-ldap', 'php-zip', 'php-fileinfo']
    enablerepo: "remi-php73"
    state: present 

